In [26]:
import pandas as pd
import numpy as np

Teams = pd.read_csv("https://raw.githubusercontent.com/menawhalen/DSCI_401/refs/heads/main/data/Teams.csv")

Teams.iloc[:,range(14,40)]

,R,AB,H,X2B,X3B,HR,BB,SO,SB,CS,...,SHO,SV,IPouts,HA,HRA,BBA,SOA,E,DP,FP
0,401,1372,426,70,37,3,60.0,19.0,73.0,16.0,...,1,3,828,367,2,42,23,243,24,0.834
1,302,1196,323,52,21,10,60.0,22.0,69.0,21.0,...,0,1,753,308,6,28,22,229,16,0.829
2,249,1186,328,35,40,7,26.0,25.0,18.0,8.0,...,0,0,762,346,13,53,34,234,15,0.818
3,137,746,178,19,8,2,33.0,9.0,16.0,4.0,...,1,0,507,261,5,21,17,163,8,0.803
4,302,1404,403,43,21,1,33.0,15.0,46.0,15.0,...,1,0,879,373,7,42,22,235,14,0.840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2980,706,5351,1303,261,22,198,478.0,1341.0,89.0,22.0,...,15,50,4251,1234,152,608,1225,84,137,0.986
2981,857,5507,1336,288,36,222,585.0,1542.0,88.0,42.0,...,13,42,4367,1264,184,436,1478,80,130,0.986
2982,625,5405,1254,225,24,167,433.0,1381.0,106.0,29.0,...,3,31,4273,1402,232,513,1239,83,146,0.986
2983,846,5476,1455,285,13,262,496.0,1218.0,81.0,20.0,...,14,34,4216,1257,209,473,1468,90,122,0.984
2984,724,5385,1388,272,20,182,573.0,1303.0,56.0,26.0,...,8,36,4183,1364,247,548,1346,96,116,0.983

Using a for loop to calculate column-wise averages.

In [ ]:
averages = np.zeros(26)
for i in range(14,40):
  averages[i-14] = np.mean(Teams.iloc[:,i])

print(averages)

[6.81030821e+02 5.12899095e+03 1.33942044e+03 2.28669682e+02
 4.56730318e+01 1.05865997e+02 4.73557306e+02 7.62133715e+02
 1.09408185e+02 4.65499303e+01 4.58210181e+01 4.41059557e+01
 6.81029816e+02 5.73405360e+02 3.84064322e+00 4.75453936e+01
 9.58760469e+00 2.44217755e+01 4.01323652e+03 1.33920000e+03
 1.05865997e+02 4.73747404e+02 7.61580570e+02 1.80784925e+02
 1.32617755e+02 9.66350419e-01]

In [ ]:
df = pd.DataFrame(averages, index=Teams.columns[14:40], columns=[1])
print(df)

                  1
R        681.030821
AB      5128.990955
H       1339.420436
X2B      228.669682
X3B       45.673032
HR       105.865997
BB       473.557306
SO       762.133715
SB       109.408185
CS        46.549930
HBP       45.821018
SF        44.105956
RA       681.029816
ER       573.405360
ERA        3.840643
CG        47.545394
SHO        9.587605
SV        24.421776
IPouts  4013.236516
HA      1339.200000
HRA      105.865997
BBA      473.747404
SOA      761.580570
E        180.784925
DP       132.617755
FP         0.966350

Defining a function to find the square root of a column

In [ ]:
def f(x):
    # return math.sqrt(x)
    return np.sqrt(x)

f([1,2,4])

array([1.        , 1.41421356, 2.        ])

## Vectorization with np.vectorize
In Python, `vectorization` is a technique that allows you to apply a function to a whole array or list of values at once, rather than using loops. This approach is not only more efficient but also takes advantage of optimized libraries like numpy for faster computation. Vectorization is especially helpful when you want to perform operations on large datasets without manually iterating over each element.

### Defining and Vectorizing a Function
1. Define the function: We start with a basic function f that returns the square root of a single value using np.sqrt.

2. Vectorize the function: We then use np.vectorize(f) to create a vectorized version of the function, stored in vf. The vectorized function can now take in lists or arrays and return the square root of each element in a single operation.

3. Apply the vectorized function: Now, we can pass an entire list (e.g., [1, 2, 3]) to vf, which returns an array with the square root of each element.

In [ ]:
vf = np.vectorize(f)
vf([1,2,3])

array([1.        , 1.41421356, 1.73205081])

In [ ]:
Teams.iloc[:,range(14,40)]

,R,AB,H,X2B,X3B,HR,BB,SO,SB,CS,...,SHO,SV,IPouts,HA,HRA,BBA,SOA,E,DP,FP
0,401,1372,426,70,37,3,60.0,19.0,73.0,16.0,...,1,3,828,367,2,42,23,243,24,0.834
1,302,1196,323,52,21,10,60.0,22.0,69.0,21.0,...,0,1,753,308,6,28,22,229,16,0.829
2,249,1186,328,35,40,7,26.0,25.0,18.0,8.0,...,0,0,762,346,13,53,34,234,15,0.818
3,137,746,178,19,8,2,33.0,9.0,16.0,4.0,...,1,0,507,261,5,21,17,163,8,0.803
4,302,1404,403,43,21,1,33.0,15.0,46.0,15.0,...,1,0,879,373,7,42,22,235,14,0.840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2980,706,5351,1303,261,22,198,478.0,1341.0,89.0,22.0,...,15,50,4251,1234,152,608,1225,84,137,0.986
2981,857,5507,1336,288,36,222,585.0,1542.0,88.0,42.0,...,13,42,4367,1264,184,436,1478,80,130,0.986
2982,625,5405,1254,225,24,167,433.0,1381.0,106.0,29.0,...,3,31,4273,1402,232,513,1239,83,146,0.986
2983,846,5476,1455,285,13,262,496.0,1218.0,81.0,20.0,...,14,34,4216,1257,209,473,1468,90,122,0.984
2984,724,5385,1388,272,20,182,573.0,1303.0,56.0,26.0,...,8,36,4183,1364,247,548,1346,96,116,0.983

## Using apply in Python with Pandas
The `.apply()` function in Pandas is incredibly versatile and allows you to apply a function along either rows or columns of a DataFrame. This is particularly useful when you want to perform custom operations on a DataFrame without needing to write loops.

### Example: Applying a Function Across Columns or Rows
Suppose we have a DataFrame Teams with several numeric columns, and we want to calculate the mean for each column within a specific range of columns.

In [ ]:
Teams.iloc[:, range(14, 40)].apply(np.mean, axis=0)

R          681.030821
AB        5128.990955
H         1339.420436
X2B        228.669682
X3B         45.673032
HR         105.865997
BB         473.557306
SO         762.133715
SB         109.408185
CS          46.549930
HBP         45.821018
SF          44.105956
RA         681.029816
ER         573.405360
ERA          3.840643
CG          47.545394
SHO          9.587605
SV          24.421776
IPouts    4013.236516
HA        1339.200000
HRA        105.865997
BBA        473.747404
SOA        761.580570
E          180.784925
DP         132.617755
FP           0.966350
dtype: float64

Using .apply(): We use .apply(np.mean, axis=0) to calculate the mean of each column.

- np.mean is the function applied to each selected column.
- axis=0 specifies that the function should be applied across each column.
- Setting axis=1 would apply the function across rows instead, calculating the mean for each row.

### Selecting Numeric Columns and Applying Functions in Python
This code demonstrates how to select only the numeric columns in a DataFrame and apply a function to them. Using this approach can be useful when your DataFrame contains a mix of data types (e.g., integers, strings, floats) and you want to perform calculations only on the numeric columns.

In [ ]:
#Pull out the numeric variables without the index
numerics = ['int16', 'int32', 'int64']
Teams_sub = Teams.select_dtypes(include=numerics)
Teams_sub.apply(np.mean,axis = 0)

yearID    1958.863652
Rank         4.039196
G          150.006030
W           74.611055
L           74.611055
R          681.030821
AB        5128.990955
H         1339.420436
X2B        228.669682
X3B         45.673032
HR         105.865997
RA         681.029816
ER         573.405360
CG          47.545394
SHO          9.587605
SV          24.421776
IPouts    4013.236516
HA        1339.200000
HRA        105.865997
BBA        473.747404
SOA        761.580570
E          180.784925
DP         132.617755
BPF        100.189950
PPF        100.212395
dtype: float64

## Using Lambda Functions with apply
Lambda functions are a way to create quick, one-line functions for a specific task without defining a full function elsewhere. Here, theyâ€™re used in combination with `.apply()` to do something specific for each group of data, like selecting the "first" or "last" entry. The point of learning this is to practice creating small, task-specific functions to operate on data. Lambda functions help make code shorter and more readable when the task is straightforward.

### Applying Functions to Groups of Data
This is where `.apply()` shines because it allows you to take action on each group separately. The idea here is to see that you can split data up and apply different logic to each section as needed. Itâ€™s a foundation for many data tasks because it mimics real-world organization: you often need to analyze or report on data by category, date, or group.

In [ ]:
angels = Teams[Teams.franchID == "ANA"].groupby(["teamID","name"])


first = angels.apply(lambda x: x.head(1))[["name","yearID"]]
first.reset_index(drop=True, inplace=True) ## needed for formatting

last = angels.apply(lambda x: x.tail(1))[["name","yearID"]]
last.reset_index(drop=True, inplace=True)

merg = first.merge(last, on = "name")
merg = merg.rename(columns = {"yearID_x":"start","yearID_y":"end"})
print(merg)

                            name  start   end
0                 Anaheim Angels   1997  2004
1              California Angels   1965  1996
2             Los Angeles Angels   1961  1964
3  Los Angeles Angels of Anaheim   2005  2021

<ipython-input-11-47afee2462e1>:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  first = angels.apply(lambda x: x.head(1))[["name","yearID"]]
<ipython-input-11-47afee2462e1>:7: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  last = angels.apply(lambda x: x.tail(1))[["name","yearID"]]

In [ ]:
#applying again what is the length of each character
merg.name.apply(len)

0    14
1    17
2    18
3    29
Name: name, dtype: int64

## Iterating over your own function

In [ ]:
def top5(data, team_name):
  out = data[data.name == team_name][["teamID","yearID","W","L","name"]].sort_values("W", ascending = False).head(5)
  return(out)

top5(Teams, "New York Yankees")

     teamID  yearID    W   L              name
2283    NYA    1998  114  48  New York Yankees
824     NYA    1927  110  44  New York Yankees
1371    NYA    1961  109  53  New York Yankees
904     NYA    1932  107  47  New York Yankees
1016    NYA    1939  106  45  New York Yankees

Great but now we want to iterate over all the ANA team names

In [ ]:
angels_names = merg["name"]
angels_names.head()

0                   Anaheim Angels
1                California Angels
2               Los Angeles Angels
3    Los Angeles Angels of Anaheim
Name: name, dtype: object

In [ ]:
# Use map to apply the `top5` function to each team name
top_teams = list(map(lambda name: top5(Teams, name), angels_names))
for team in top_teams:
    print(team)

     teamID  yearID   W   L            name
2385    ANA    2002  99  63  Anaheim Angels
2445    ANA    2004  92  70  Anaheim Angels
2265    ANA    1998  85  77  Anaheim Angels
2237    ANA    1997  84  78  Anaheim Angels
2325    ANA    2000  82  80  Anaheim Angels
     teamID  yearID   W   L               name
1842    CAL    1982  93  69  California Angels
1946    CAL    1986  92  70  California Angels
2024    CAL    1989  91  71  California Angels
1920    CAL    1985  90  72  California Angels
1764    CAL    1979  88  74  California Angels
     teamID  yearID   W   L                name
1386    LAA    1962  86  76  Los Angeles Angels
1426    LAA    1964  82  80  Los Angeles Angels
1367    LAA    1961  70  91  Los Angeles Angels
1406    LAA    1963  70  91  Los Angeles Angels
     teamID  yearID    W   L                           name
2578    LAA    2008  100  62  Los Angeles Angels of Anaheim
2757    LAA    2014   98  64  Los Angeles Angels of Anaheim
2608    LAA    2009   97  65  Los Angeles Angels of Anaheim
2488    LAA    2005   95  67  Los Angeles Angels of Anaheim
2548    LAA    2007   94  68  Los Angeles Angels of Anaheim

## Map
The map function in Python is a built-in function that allows you to apply a specified function to each item in an iterable (like a list or a set) and returns a new iterator with the results. Itâ€™s especially useful when you want to apply the same operation to every element in a collection without writing a loop.
```
map(function, iterable)
```
- function: This is the function you want to apply to each element in the iterable. It can be a regular function or a lambda function (an anonymous function).
- iterable: This is the sequence of items (like a list, tuple, or set) that map will apply the function to.

### How It Works:
1. Function Application: map takes each element from the iterable and applies the specified function to it.
2. Returns an Iterator: Instead of directly returning a new list, map returns a special object called an iterator. This is memory efficient, especially for large datasets, because it computes each result only when needed.
3. Casting to a List: Since map returns an iterator, you often see it wrapped in list() when you want all results at once, as in list(map(...)).

Example with Basic Functions
Hereâ€™s a simple example to illustrate how map works with a function that squares each element in a list:

In [27]:
# Define a simple function to square a number
def square(x):
    return x ** 2

# Apply the function to each item in the list
numbers = [1, 2, 3, 4]
squared_numbers = map(square, numbers)

# Convert map object to list to see the results
print(list(squared_numbers))
squared_numbers

[1, 4, 9, 16]

### Using map with a Lambda Function
For small, quick operations, you can use a lambda function inside map instead of defining a separate function. Hereâ€™s the previous example rewritten using a lambda:

In [28]:
squared_numbers = map(lambda x: x ** 2, numbers)
print(list(squared_numbers))

[1, 4, 9, 16]

In [29]:
str(squared_numbers)

'<map object at 0x7d99a0d63520>'

## map v apply in python
- map: A built-in Python function primarily designed to apply a single function to each element in a Python iterable (e.g., list, tuple). map returns a map object (an iterator) that generates results lazily, making it memory efficient.

- apply: A method available in the Pandas library, designed specifically for applying functions to either rows or columns of a DataFrame or Series. It is widely used for DataFrame manipulations where the function requires context on each row or column.

### Typical Usage

- `map`: Typically used for transforming lists, dictionaries, or similar collections outside of Pandas. Since it works with individual elements, itâ€™s best suited for element-wise transformations and works well with simpler operations that donâ€™t depend on DataFrame context.

- `apply`: Often used within a DataFrame to apply operations that might require row or column context. You can specify axis=0 to apply functions across columns or axis=1 to apply across rows, making it highly flexible for row-wise or column-wise transformations.

In [ ]:
# Example with a list
numbers = [1, 2, 3, 4]
squared = list(map(lambda x: x ** 2, numbers))
print(squared)  # [1, 4, 9, 16]

In [ ]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [10, 20, 30]})
df['A_squared'] = df['A'].apply(lambda x: x ** 2)
print(df)

   A   B  A_squared
0  1  10          1
1  2  20          4
2  3  30          9

### Performance and Efficiency
- `map`: Faster for applying functions to basic Python data structures due to its native iterator-based design. Ideal for simple element-wise operations that donâ€™t require complex logic or row/column context.

- `apply`: Can be slower with large DataFrames because itâ€™s more flexible and provides row or column context. However, it is highly compatible with DataFrames and can handle complex operations.

### Return Type
- `map`: Returns an iterator (which can be converted to a list or other collection), meaning it is memory efficient for large datasets when used without conversion to a list.

- `apply`: Returns a Pandas Series or DataFrame, depending on whatâ€™s applied and the axis specified. This means it integrates seamlessly with other DataFrame methods and operations.

### Common use cases

- `map`: Transforming elements of a list, dictionary keys/values, or Series with simple, element-wise functions. In Pandas, map is also used to map values in a Series based on a dictionary or function.

- `apply`: Applying row or column-based transformations that require context, or aggregating functions that may need additional arguments, such as lambda functions that compute row-specific operations.

In [ ]:
# Example: Using map with a dictionary in Pandas
df['A_mapped'] = df['A'].map({1: 'one', 2: 'two', 3: 'three'})
print(df.A_mapped)

0      one
1      two
2    three
Name: A_mapped, dtype: object

In [ ]:
# Example: Summing values in each row
df['row_sum'] = df.apply(lambda row: row['A'] + row['B'], axis=1)
print(df.row_sum)

0    11
1    22
2    33
Name: row_sum, dtype: int64

## On your own..

Create a Win Percentage Calculation - Create a win percentage column (W/G)

Map a Categorization of Team Performance: Create a custom function to classify teams based on their win percentage (e.g., "Good" if above 0.5, "Average" if between 0.3-0.5, and "Poor" if below 0.3). Use map to apply this function across the win_percentage column.

Using babynames:

Apply a Gender-based Proportion Calculation: For a given year, calculate the proportion of each name within the gender group and add it as a new column. Use groupby to isolate each year, then use apply to calculate proportions.

Apply Grouped Aggregations: Group the data by name and use apply to find the first and last year each name was used (use your name).

In [32]:
Teams['win_percentage'] = Teams['W']/Teams['G']

In [34]:
def perf_score(win_perc):
  if win_perc > 0.5:
    return "Good"
  elif win_perc > 0.3:
    return "Average"
  else:
    return "Poor"

Teams['perf_score'] = Teams['win_percentage'].map(perf_score)
print(Teams['perf_score'])

0          Good
1          Good
2       Average
3       Average
4       Average
         ...
2980       Good
2981       Good
2982    Average
2983       Good
2984    Average
Name: perf_score, Length: 2985, dtype: object

In [42]:
babynames = pd.read_csv("https://raw.githubusercontent.com/gjm112/DSCI401/refs/heads/main/data/babynames.csv")
babynames.head()

   year sex       name     n      prop
0  1880   F       Mary  7065  0.072384
1  1880   F       Anna  2604  0.026679
2  1880   F       Emma  2003  0.020521
3  1880   F  Elizabeth  1939  0.019866
4  1880   F     Minnie  1746  0.017888

In [43]:
babynames['prop_name'] = babynames.groupby(['name','sex'])['n'].transform(lambda x: x / x.sum())
babynames.head()

   year sex       name     n      prop  prop_name
0  1880   F       Mary  7065  0.072384   0.001713
1  1880   F       Anna  2604  0.026679   0.002931
2  1880   F       Emma  2003  0.020521   0.003063
3  1880   F  Elizabeth  1939  0.019866   0.001190
4  1880   F     Minnie  1746  0.017888   0.010997

In [49]:
m = babynames[babynames['name'].apply(lambda x: x[0] == "M")]
m.head()

    year sex      name     n      prop  prop_name
0   1880   F      Mary  7065  0.072384   0.001713
4   1880   F    Minnie  1746  0.017888   0.010997
5   1880   F  Margaret  1578  0.016167   0.001266
15  1880   F    Martha  1040  0.010655   0.001896
20  1880   F     Maude   858  0.008791   0.018852

In [56]:
earliest = m.groupby(['name', 'sex'])['year'].apply(min)
latest = m.groupby(['name', 'sex'])['year'].apply(max)

combinde_m = pd.merge(earliest, latest, on = ['name', 'sex'])

combinde_m['use_time'] = combinde_m['year_y'] - combinde_m['year_x']
combinde_m.head()

<ipython-input-56-b221afdb4c3c>:1: FutureWarning: The provided callable <built-in function min> is currently using np.minimum.reduce. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.minimum.reduce instead.
  earliest = m.groupby(['name', 'sex'])['year'].apply(min)
<ipython-input-56-b221afdb4c3c>:2: FutureWarning: The provided callable <built-in function max> is currently using np.maximum.reduce. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.maximum.reduce instead.
  latest = m.groupby(['name', 'sex'])['year'].apply(max)

             year_x  year_y  use_time
name    sex
Ma      F      1924    2012        88
Maadhav M      2013    2014         1
Maaha   F      2001    2001         0
Maahi   F      2004    2017        13
Maahika F      2012    2012         0

In [57]:
combinde_m.sort_values('use_time', ascending = False).head()

              year_x  year_y  use_time
name     sex
Mercedes F      1880    2017       137
Melissa  F      1880    2017       137
Mahala   F      1880    2017       137
Marian   F      1880    2017       137
Mariah   F      1880    2017       137

In [60]:
combinde_m[combinde_m['use_time'] == 137].groupby('sex').count()

     year_x  year_y  use_time
sex
F        77      77        77
M        57      57        57